package io.acaeronte.jdbc.mapper.annotations;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

@Target({ElementType.FIELD})
@Retention(RetentionPolicy.RUNTIME)
public @interface Column {
    String name();
    boolean required() default false;
    String defaultValue() default "";
    boolean autoGenerated() default false;
    boolean  allowLiteralCondition() default false;
    String historicPartitionName() default "";
}
